apiVersion: apps/v1
kind: Deployment

metadata:
  name: online-shop-deployment
  namespace: online-shop
  labels:
    app: online-shop-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-shop-app

  template:
    metadata:
      name: online-shop-pod
      labels:
        app: online-shop-app

    spec:
      containers:
      - name: online-shop-container
        image: nitingumberdev/online_shop_app:v0.2
        ports:
         - containerPort: 80


