apiVersion: v1
kind: Service

metadata:
  name: online-shop-svc
  namespace: online-shop

spec:
  selector:
    app: online-shop-app

  ports:
  - protocol: TCP
    port: 5173 # Service/cluster
    targetPort: 5173 # pod/container
